name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [recreate_site]
    

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: tboby/cag-register-fsharp-data
          path: data
          token: ${{ secrets.CAG_DATA_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: main/package-lock.json
          
      
      - name: Restore .NET tools
        run: dotnet tool restore
        working-directory: main

      - name: Install npm dependencies
        run: npm install
        working-directory: main

      - name: Build project
        run: dotnet run PublishClient
        working-directory: main
        
      - name: Copy data files
        run: |
          mkdir -p $GITHUB_WORKSPACE/main/deploy/public/api-responses
          cp $GITHUB_WORKSPACE/data/* $GITHUB_WORKSPACE/main/deploy/public/api-responses

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # upload entire directory
          path: 'main/deploy/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

